### PR TITLE
Fixed: alphabetical ordering, broken lists, and missing images

### PR DESCRIPTION
**Pull request by einar-saukas**

### CODE REVIEW

**Comment by boriel** [comment]
Thanks, @einar-saukas 
One thing: The list were supposed to be sorted by publication time (from most recent to oldest one), not alphabetically.

**Comment by einar-saukas** [comment]
Hi Boriel,

The problem is, the entire list was already sorted alphabetically, except for a couple items at the top! It has been this way for years, even before it was moved here... Actually even these few new items at the top were not sorted by release order between themselves.

Another problem is, this page lost its index of game titles when it was moved here. Without alphabetical ordering and without indexing, this list looks very confusing IMHO. Frankly I see no practical advantage in release order over alphabetical, also considering that there's a great variation in game quality that doesn't seem related to year of release.

Anyway it's your call :)

**Comment by boriel** [comment]
I see. Then let's merge it this way.
Many thanks!

**Comment by einar-saukas** [comment]
You are welcome!

**Pull request merged**
